"""add stage column

Revision ID: eb296a376361
Revises: 95582106f103
Create Date: 2026-07-28 00:57:06.985609

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eb296a376361'
down_revision: str | Sequence[str] | None = '95582106f103'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "research_tasks",
    sa.Column(
        "stage",
        sa.Enum(
            "queued",
            "planning",
            "query_generation",
            "web_search",
            "arxiv_search",
            "merging",
            "writing_report",
            "summarizing",
            "finalizing",
            "completed",
            "failed",
            name="task_stage",
        ),
        nullable=False,
        server_default="queued",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_tasks', 'stage')
    # ### end Alembic commands ###
